apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raool1/nifi-k8s-cluster-autoscaling.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - nifi-secure.yaml
    chart: nifi
    repoURL: https://cetic.github.io/helm-charts
    targetRevision: 0.1.4
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

