apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raool1/nifi-k8s-cluster-autoscaling.git
    targetRevision: HEAD
    path: nifi                      # 👈 Path to your local chart in repo
    helm:
      valueFiles:
        - nifi-secure.yaml          # 👈 File inside that `nifi/` folder
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

